import Head from 'next/head'
import Link from 'next/link'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Wellcome Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="">
        <div className='mx-auto max-w-7xl text-center'>
        <h1 className="font-bold text-5xl mt-20">
         <span className='group cursor-pointer'>Welcome to <a className='group-hover:text-blue-500 group-hover:underline' >Coder.com</a></span>
        </h1>
        <p className=" font-medium text-lg mt-10">
          Get started by editing
        </p>
        <hr className='mt-3 border-indigo-500 max-w-7xl mx-auto w-80'/>
        <div className='mt-28'>
          <div className='flex justify-center items-center flex-wrap 2xl:mx-72 xl:mx-64 md:mx-56'>
            <Link href="/blog"><a><div className='ring-1 rounded-lg ring-slate-300 hover:ring-indigo-500 group cursor-pointer p-5 mx-5 mt-5 h-40 w-56'>
              <h3 className='text-left font-semibold text-xl group-hover:text-indigo-500'>Blog →</h3>
              <p className='font-medium text-left pt-6 group-hover:text-indigo-500'>Explore Coding blogs and many more.</p>
            </div></a></Link>
            <div className='ring-1 rounded-lg ring-slate-300 hover:ring-indigo-500 group cursor-pointer p-5 mx-5 mt-5 h-40 w-56'>
              <h3 className='text-left font-semibold text-xl group-hover:text-indigo-500'>Learn →</h3>
              <p className='font-medium text-left pt-6 group-hover:text-indigo-500'>Explore Coding and learn anythig .</p>
            </div>
            <div className='ring-1 rounded-lg ring-slate-300 hover:ring-indigo-500 group cursor-pointer p-5 mx-5 mt-5 h-40 w-56'>
              <h3 className='text-left font-semibold text-xl group-hover:text-indigo-500'>Docs →</h3>
              <p className='font-medium text-left pt-6 group-hover:text-indigo-500'>Explore Coding blogs and many more.</p>
            </div>
            <div className='ring-1 rounded-lg ring-slate-300 group  hover:ring-indigo-500 cursor-pointer p-5 mx-5 mt-5 h-40 w-56'>
              <h3 className='text-left font-semibold text-xl group-hover:text-indigo-500'>More →</h3>
              <p className='font-medium text-left pt-6 group-hover:text-indigo-500'>Explore Coding blogs and many more.</p>
            </div>
          </div>
        </div>
        </div>
        </main>
        </div>
  )
}
